// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4xNRr1gwy6CaLv2J3KSgvtnard706TN0',
    appId: '1:129689713326:web:a5c43c42fd7f8f66a64b3f',
    messagingSenderId: '129689713326',
    projectId: 'madlab10socialmediaapp',
    authDomain: 'madlab10socialmediaapp.firebaseapp.com',
    storageBucket: 'madlab10socialmediaapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANFOWUdzQAf1yLvLBsveEoa8flganqen0',
    appId: '1:129689713326:android:3816bd9dbd3e6f48a64b3f',
    messagingSenderId: '129689713326',
    projectId: 'madlab10socialmediaapp',
    storageBucket: 'madlab10socialmediaapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAif9ogaxGJgbPKqoZhjNf0IbROUPq-P3s',
    appId: '1:129689713326:ios:5a9e7990ba1565fca64b3f',
    messagingSenderId: '129689713326',
    projectId: 'madlab10socialmediaapp',
    storageBucket: 'madlab10socialmediaapp.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAif9ogaxGJgbPKqoZhjNf0IbROUPq-P3s',
    appId: '1:129689713326:ios:5a9e7990ba1565fca64b3f',
    messagingSenderId: '129689713326',
    projectId: 'madlab10socialmediaapp',
    storageBucket: 'madlab10socialmediaapp.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4xNRr1gwy6CaLv2J3KSgvtnard706TN0',
    appId: '1:129689713326:web:186898f48b2ab617a64b3f',
    messagingSenderId: '129689713326',
    projectId: 'madlab10socialmediaapp',
    authDomain: 'madlab10socialmediaapp.firebaseapp.com',
    storageBucket: 'madlab10socialmediaapp.firebasestorage.app',
  );

}